---
- name: Apply network resources
  hosts: ios
  gather_facts: false

  tasks:
    - name: Apply interface resource
      cisco.ios.interfaces:
        state: merged
        config: "{{ interfaces }}"
